version: "3.4"

services:
  workshop.wwwapi:
    image: workshopwwwapi
    build:
      context: .
      dockerfile: workshop.wwwapi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - doctorpatient-network
    depends_on:
      doctorpatient.database:
        condition: service_healthy
  doctorpatient.database:
    container_name: "doctorpatient.database" # host url for my postgres db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - doctorpatient-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  doctorpatient-network:
    driver: bridge
