using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace workshop.wwwapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "doctors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    full_name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_doctors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "patients",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    full_name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_patients", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "appointments",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    doctor_id = table.Column<int>(type: "integer", nullable: false),
                    patient_id = table.Column<int>(type: "integer", nullable: false),
                    appointment_time = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_appointments", x => x.id);
                    table.ForeignKey(
                        name: "FK_appointments_doctors_doctor_id",
                        column: x => x.doctor_id,
                        principalTable: "doctors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_appointments_patients_patient_id",
                        column: x => x.patient_id,
                        principalTable: "patients",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "doctors",
                columns: new[] { "id", "full_name" },
                values: new object[,]
                {
                    { 1, "Master Dr. Frederick Sinclair-Fitzgerald" },
                    { 2, "Prof. Dr. Genevieve Montague-Smythe" },
                    { 3, "Prof. Dr. Daphne Derbyshire-Langford" },
                    { 4, "Doc. Leopold Fitzroy-Davenport" },
                    { 5, "Dr. Felicity Vanderbilt-Astor" },
                    { 6, "Dr. Master Oliver Sterling-Montgomery" },
                    { 7, "Doctor Beatrice Kensington-Rowe" },
                    { 8, "Dr. PhD Edmund Derbyshire-Langford" },
                    { 9, "Dr. PhD Henrietta Ashford-Lexington" },
                    { 10, "Prof. Dr. Ophelia Ravenswood-Grantham" },
                    { 11, "Doctor Dorian Blackwood-Mornington" },
                    { 12, "Doc. Maximilian Pembroke-Ellington" },
                    { 13, "Doctor Alexander Fairbanks-Crowley" },
                    { 14, "Dr. Maximilian Wentworth-Fitzwilliam" },
                    { 15, "Dr. Master Felicity Vanderbilt-Astor" }
                });

            migrationBuilder.InsertData(
                table: "patients",
                columns: new[] { "id", "full_name" },
                values: new object[,]
                {
                    { 1, "Frank Davis" },
                    { 2, "Grace Smith" },
                    { 3, "Anna Harris" },
                    { 4, "Ben Davis" },
                    { 5, "Frank Brown" },
                    { 6, "Claire Johnson" },
                    { 7, "Claire Moore" },
                    { 8, "Frank Anderson" },
                    { 9, "John Wilson" },
                    { 10, "Ben Moore" },
                    { 11, "Dave Jackson" },
                    { 12, "Chris Davis" },
                    { 13, "Claire Martinez" },
                    { 14, "Beth White" },
                    { 15, "Ben Taylor" },
                    { 16, "Julia Thomas" },
                    { 17, "Emily Thomas" },
                    { 18, "Chris Brown" },
                    { 19, "Grace Johnson" },
                    { 20, "Beth Davis" },
                    { 21, "Beth White" },
                    { 22, "Emily Smith" },
                    { 23, "Grace Miller" },
                    { 24, "Ben Anderson" },
                    { 25, "Anna Jackson" },
                    { 26, "John Brown" },
                    { 27, "Julia Wilson" },
                    { 28, "Diane Robinson" },
                    { 29, "Ben Davis" },
                    { 30, "Chris Thomas" },
                    { 31, "Anna Jackson" },
                    { 32, "Greg Martin" },
                    { 33, "Claire Garcia" },
                    { 34, "Dave Williams" },
                    { 35, "John Thomas" },
                    { 36, "Ben White" },
                    { 37, "Julia Jackson" },
                    { 38, "Claire Johnson" },
                    { 39, "Julia Williams" },
                    { 40, "John Smith" },
                    { 41, "Ian Wilson" },
                    { 42, "John Garcia" },
                    { 43, "Diane Thomas" },
                    { 44, "Claire Thompson" },
                    { 45, "Chris Wilson" },
                    { 46, "Grace Harris" },
                    { 47, "John Martin" },
                    { 48, "Anna Wilson" },
                    { 49, "Ian Harris" },
                    { 50, "Anna Williams" },
                    { 51, "Frank Brown" },
                    { 52, "Emily White" },
                    { 53, "Greg Davis" },
                    { 54, "Emily Thomas" },
                    { 55, "Anna Anderson" },
                    { 56, "Greg Brown" },
                    { 57, "Emily Anderson" },
                    { 58, "Diane Taylor" },
                    { 59, "John Thomas" },
                    { 60, "Frank Thomas" },
                    { 61, "Chris Taylor" },
                    { 62, "Chris Robinson" },
                    { 63, "Dave Thompson" },
                    { 64, "Frank Garcia" },
                    { 65, "John Brown" },
                    { 66, "Ian Thomas" },
                    { 67, "Diane Martinez" },
                    { 68, "Claire Davis" },
                    { 69, "Dave Martin" },
                    { 70, "Jack Williams" },
                    { 71, "John Taylor" },
                    { 72, "Diane Anderson" },
                    { 73, "Grace Thompson" },
                    { 74, "Ben Jackson" },
                    { 75, "Chris Jackson" },
                    { 76, "Emily Smith" },
                    { 77, "Julia Brown" },
                    { 78, "Claire Smith" },
                    { 79, "Emily Harris" },
                    { 80, "Anna Brown" },
                    { 81, "Greg Harris" },
                    { 82, "Greg Williams" },
                    { 83, "Ben Miller" },
                    { 84, "Ian Garcia" },
                    { 85, "Beth White" },
                    { 86, "Beth White" },
                    { 87, "Frank Martinez" },
                    { 88, "Anna Miller" },
                    { 89, "Emily Williams" },
                    { 90, "Ian Jackson" },
                    { 91, "Anna Jackson" },
                    { 92, "Greg Harris" },
                    { 93, "Emily Martin" },
                    { 94, "Claire Taylor" },
                    { 95, "Ian Miller" },
                    { 96, "Claire Martinez" },
                    { 97, "Grace Robinson" },
                    { 98, "Jack Smith" },
                    { 99, "Jack Miller" },
                    { 100, "Frank Jackson" },
                    { 101, "Chris Wilson" },
                    { 102, "Claire Brown" },
                    { 103, "Grace Moore" },
                    { 104, "Anna Brown" },
                    { 105, "Ben Martinez" },
                    { 106, "Ian White" },
                    { 107, "Julia Martinez" },
                    { 108, "Emily Robinson" },
                    { 109, "Chris White" },
                    { 110, "Beth Smith" },
                    { 111, "Anna Miller" },
                    { 112, "Chris Moore" },
                    { 113, "Julia Thompson" },
                    { 114, "Chris Johnson" },
                    { 115, "Beth Anderson" },
                    { 116, "Emily Moore" },
                    { 117, "Julia Martinez" },
                    { 118, "Ian Anderson" },
                    { 119, "Ian Smith" },
                    { 120, "Chris Wilson" },
                    { 121, "Claire Jackson" },
                    { 122, "Frank Garcia" },
                    { 123, "Grace Williams" },
                    { 124, "Diane Johnson" },
                    { 125, "Claire Anderson" },
                    { 126, "Beth Harris" },
                    { 127, "Anna Williams" },
                    { 128, "Dave Miller" },
                    { 129, "Beth Williams" },
                    { 130, "Diane Davis" },
                    { 131, "Grace Anderson" },
                    { 132, "Emily Johnson" },
                    { 133, "Diane Garcia" },
                    { 134, "Grace Harris" },
                    { 135, "Chris Thompson" },
                    { 136, "Ben Moore" },
                    { 137, "Jack Martin" },
                    { 138, "Grace Smith" },
                    { 139, "Emily Garcia" },
                    { 140, "Julia Garcia" },
                    { 141, "Greg Moore" },
                    { 142, "Dave Garcia" },
                    { 143, "Claire Garcia" },
                    { 144, "Emily Thomas" },
                    { 145, "Emily Thomas" },
                    { 146, "Grace Wilson" },
                    { 147, "John Johnson" },
                    { 148, "Beth Brown" },
                    { 149, "Ben Miller" },
                    { 150, "Jack Harris" },
                    { 151, "John Martinez" },
                    { 152, "Diane Garcia" },
                    { 153, "Julia Thompson" },
                    { 154, "Emily Taylor" },
                    { 155, "Julia Davis" },
                    { 156, "Anna Smith" },
                    { 157, "Emily Johnson" },
                    { 158, "Diane Miller" },
                    { 159, "Grace Martin" },
                    { 160, "Beth Harris" },
                    { 161, "Diane Martin" },
                    { 162, "Emily Brown" },
                    { 163, "Ben Taylor" },
                    { 164, "Chris Miller" },
                    { 165, "Anna Moore" },
                    { 166, "Ian Johnson" },
                    { 167, "Beth Wilson" },
                    { 168, "Chris Martin" },
                    { 169, "Claire Jackson" },
                    { 170, "Emily Wilson" },
                    { 171, "John Johnson" },
                    { 172, "Frank Jackson" },
                    { 173, "Grace Miller" },
                    { 174, "Anna Johnson" },
                    { 175, "Chris Davis" },
                    { 176, "Frank Taylor" },
                    { 177, "Anna Garcia" },
                    { 178, "Anna Garcia" },
                    { 179, "Diane Taylor" },
                    { 180, "John Jackson" },
                    { 181, "Emily Davis" },
                    { 182, "Ben Wilson" },
                    { 183, "Greg Johnson" },
                    { 184, "Grace Smith" },
                    { 185, "Diane Thomas" },
                    { 186, "Diane Williams" },
                    { 187, "Dave Harris" },
                    { 188, "Anna Brown" },
                    { 189, "Ben Brown" },
                    { 190, "Anna Martin" },
                    { 191, "Anna Johnson" },
                    { 192, "Julia Williams" },
                    { 193, "Grace Davis" },
                    { 194, "Chris Davis" },
                    { 195, "Diane Anderson" },
                    { 196, "Beth Anderson" },
                    { 197, "Emily Martin" },
                    { 198, "John Thomas" },
                    { 199, "Claire Garcia" },
                    { 200, "Chris Thomas" },
                    { 201, "Beth Johnson" },
                    { 202, "Claire Miller" },
                    { 203, "Ian Thomas" },
                    { 204, "Grace Martinez" },
                    { 205, "John Martinez" },
                    { 206, "Grace Wilson" },
                    { 207, "Jack Martinez" },
                    { 208, "Emily Davis" },
                    { 209, "Diane Wilson" },
                    { 210, "Grace Garcia" },
                    { 211, "Chris Jackson" },
                    { 212, "Claire Martinez" },
                    { 213, "Anna Miller" },
                    { 214, "Julia Moore" },
                    { 215, "Julia Wilson" },
                    { 216, "Grace Smith" },
                    { 217, "Frank Miller" },
                    { 218, "Claire Thomas" },
                    { 219, "Grace Moore" },
                    { 220, "Jack Jackson" },
                    { 221, "Ben Wilson" },
                    { 222, "Diane Thompson" },
                    { 223, "Diane Martinez" },
                    { 224, "John Harris" },
                    { 225, "Julia Miller" },
                    { 226, "Frank Thomas" },
                    { 227, "Emily Johnson" },
                    { 228, "Frank White" },
                    { 229, "Jack Brown" },
                    { 230, "Beth Wilson" },
                    { 231, "Jack Jackson" },
                    { 232, "Anna Garcia" },
                    { 233, "Diane Miller" },
                    { 234, "Ian Smith" },
                    { 235, "Jack Harris" },
                    { 236, "Grace Smith" },
                    { 237, "Ben Anderson" },
                    { 238, "Ian Robinson" },
                    { 239, "Frank Thompson" },
                    { 240, "Grace Williams" },
                    { 241, "Ian Williams" },
                    { 242, "Jack Wilson" },
                    { 243, "Julia Williams" },
                    { 244, "Dave Thompson" },
                    { 245, "Dave Thomas" },
                    { 246, "Claire Jackson" },
                    { 247, "Frank Anderson" },
                    { 248, "John Martin" },
                    { 249, "Ben Martinez" },
                    { 250, "Chris White" },
                    { 251, "Greg Smith" },
                    { 252, "Dave Martin" },
                    { 253, "Ben Wilson" },
                    { 254, "Dave Harris" },
                    { 255, "Frank Johnson" },
                    { 256, "Emily Davis" },
                    { 257, "Emily Taylor" },
                    { 258, "Diane Moore" },
                    { 259, "Frank Robinson" },
                    { 260, "Claire Williams" },
                    { 261, "Claire Thompson" },
                    { 262, "Anna Thomas" },
                    { 263, "Chris Jackson" },
                    { 264, "Frank Thomas" },
                    { 265, "Dave Moore" },
                    { 266, "Anna Brown" },
                    { 267, "Emily Brown" },
                    { 268, "Dave Harris" },
                    { 269, "Ian Wilson" },
                    { 270, "Jack Moore" },
                    { 271, "Julia Garcia" },
                    { 272, "Jack Miller" },
                    { 273, "John Davis" },
                    { 274, "Beth Taylor" },
                    { 275, "Dave Miller" },
                    { 276, "Julia Jackson" },
                    { 277, "Beth Jackson" },
                    { 278, "John Jackson" },
                    { 279, "Beth Anderson" },
                    { 280, "Emily Thomas" },
                    { 281, "Beth Garcia" },
                    { 282, "Emily Miller" },
                    { 283, "Beth Martinez" },
                    { 284, "Dave Wilson" },
                    { 285, "Frank White" },
                    { 286, "Greg Smith" },
                    { 287, "John Taylor" },
                    { 288, "Chris Martin" },
                    { 289, "Jack Garcia" },
                    { 290, "Beth Robinson" },
                    { 291, "Dave Martin" },
                    { 292, "Anna Garcia" },
                    { 293, "John Wilson" },
                    { 294, "Ben Wilson" },
                    { 295, "Beth Wilson" },
                    { 296, "Claire Davis" },
                    { 297, "Julia Robinson" },
                    { 298, "Grace White" },
                    { 299, "Chris Williams" },
                    { 300, "Diane Anderson" },
                    { 301, "Diane Miller" },
                    { 302, "Grace Robinson" },
                    { 303, "Ben Miller" },
                    { 304, "Claire Thompson" },
                    { 305, "Greg Harris" },
                    { 306, "John Wilson" },
                    { 307, "Julia Johnson" },
                    { 308, "Claire Taylor" },
                    { 309, "Frank Miller" },
                    { 310, "Ian Harris" },
                    { 311, "Grace Garcia" },
                    { 312, "Grace Thompson" },
                    { 313, "Greg Anderson" },
                    { 314, "Anna Taylor" },
                    { 315, "Frank Martinez" },
                    { 316, "Dave Davis" },
                    { 317, "Julia Thomas" },
                    { 318, "Frank Miller" },
                    { 319, "Beth Taylor" },
                    { 320, "Jack Wilson" },
                    { 321, "Grace Thompson" },
                    { 322, "Grace Jackson" },
                    { 323, "Emily Williams" },
                    { 324, "Greg Taylor" },
                    { 325, "Diane Davis" },
                    { 326, "Jack Anderson" },
                    { 327, "Grace Johnson" },
                    { 328, "Julia Davis" },
                    { 329, "Dave Martin" },
                    { 330, "Jack Johnson" },
                    { 331, "John Harris" },
                    { 332, "Ian Thompson" },
                    { 333, "Beth Davis" },
                    { 334, "Anna Wilson" },
                    { 335, "Ben Harris" },
                    { 336, "Grace Jackson" },
                    { 337, "Frank Garcia" },
                    { 338, "Diane Robinson" },
                    { 339, "Julia Miller" },
                    { 340, "Ben Garcia" },
                    { 341, "Claire Harris" },
                    { 342, "Julia Wilson" },
                    { 343, "Ian Robinson" },
                    { 344, "Anna Miller" },
                    { 345, "Claire Williams" },
                    { 346, "Grace Harris" },
                    { 347, "Frank Jackson" },
                    { 348, "Greg Harris" },
                    { 349, "Frank Taylor" },
                    { 350, "Chris Miller" },
                    { 351, "Claire Robinson" },
                    { 352, "Ben Williams" },
                    { 353, "Chris Martinez" },
                    { 354, "Beth Miller" },
                    { 355, "Ben Davis" },
                    { 356, "Chris Taylor" },
                    { 357, "Anna Thompson" },
                    { 358, "Beth Moore" },
                    { 359, "John Anderson" },
                    { 360, "Diane Moore" },
                    { 361, "Jack Moore" },
                    { 362, "Julia Anderson" },
                    { 363, "Emily Harris" },
                    { 364, "Emily Williams" },
                    { 365, "Anna Taylor" },
                    { 366, "Emily Miller" },
                    { 367, "Greg White" },
                    { 368, "Ben Martin" },
                    { 369, "Emily Martinez" },
                    { 370, "Beth Martinez" },
                    { 371, "Julia Robinson" },
                    { 372, "Claire Smith" },
                    { 373, "John Martinez" },
                    { 374, "John Davis" },
                    { 375, "Ian Wilson" },
                    { 376, "Grace Miller" },
                    { 377, "Dave Thomas" },
                    { 378, "Ben Wilson" },
                    { 379, "Dave White" },
                    { 380, "Claire Anderson" },
                    { 381, "Chris Harris" },
                    { 382, "Diane Thomas" },
                    { 383, "Diane Wilson" },
                    { 384, "Dave Garcia" },
                    { 385, "Ian Garcia" },
                    { 386, "Greg Jackson" },
                    { 387, "Claire White" },
                    { 388, "Greg Thompson" },
                    { 389, "Anna Brown" },
                    { 390, "Grace Harris" },
                    { 391, "Ian Jackson" },
                    { 392, "Claire Williams" },
                    { 393, "Ian Thomas" },
                    { 394, "Grace Davis" },
                    { 395, "Claire Smith" },
                    { 396, "Grace Thompson" },
                    { 397, "Frank Johnson" },
                    { 398, "Dave Smith" },
                    { 399, "Emily Taylor" },
                    { 400, "Beth Martin" },
                    { 401, "Diane Davis" },
                    { 402, "Diane White" },
                    { 403, "Emily Davis" },
                    { 404, "Emily Thompson" },
                    { 405, "Julia Robinson" },
                    { 406, "Emily Robinson" },
                    { 407, "Emily Moore" },
                    { 408, "Greg Garcia" },
                    { 409, "Grace Smith" },
                    { 410, "Claire Smith" },
                    { 411, "Ian Smith" },
                    { 412, "Dave Moore" },
                    { 413, "Anna Johnson" },
                    { 414, "Ian Martinez" },
                    { 415, "Chris Williams" },
                    { 416, "Dave Thomas" },
                    { 417, "Frank Taylor" },
                    { 418, "Ben Miller" },
                    { 419, "Emily Garcia" },
                    { 420, "Frank Moore" },
                    { 421, "John Jackson" },
                    { 422, "Dave Moore" },
                    { 423, "Ben Garcia" },
                    { 424, "Frank Martin" },
                    { 425, "Grace Moore" },
                    { 426, "Greg Martin" },
                    { 427, "Frank Anderson" },
                    { 428, "John Martin" },
                    { 429, "John Jackson" },
                    { 430, "John Martin" },
                    { 431, "Ian Moore" },
                    { 432, "Frank Brown" },
                    { 433, "John Williams" },
                    { 434, "Ben Williams" },
                    { 435, "Frank Thompson" },
                    { 436, "Claire Jackson" },
                    { 437, "Dave Williams" },
                    { 438, "Emily Smith" },
                    { 439, "Dave Martin" },
                    { 440, "Diane Jackson" },
                    { 441, "Beth Thomas" },
                    { 442, "Frank White" },
                    { 443, "Greg Thomas" },
                    { 444, "Julia Brown" },
                    { 445, "Emily Brown" },
                    { 446, "Julia Thomas" },
                    { 447, "Dave Robinson" },
                    { 448, "Claire Wilson" },
                    { 449, "Anna Miller" },
                    { 450, "Ian Brown" },
                    { 451, "Emily Jackson" },
                    { 452, "Greg Martinez" },
                    { 453, "Frank Davis" },
                    { 454, "Jack Davis" },
                    { 455, "Dave Brown" },
                    { 456, "Chris Martinez" },
                    { 457, "Jack Martinez" },
                    { 458, "Dave Robinson" },
                    { 459, "Greg Thompson" },
                    { 460, "Dave Martinez" },
                    { 461, "Dave Smith" },
                    { 462, "Chris Garcia" },
                    { 463, "Claire Jackson" },
                    { 464, "Emily Davis" },
                    { 465, "Ben Martin" },
                    { 466, "Jack Brown" },
                    { 467, "Anna Thomas" },
                    { 468, "Beth Taylor" },
                    { 469, "Frank Garcia" },
                    { 470, "John Thomas" },
                    { 471, "Beth Robinson" },
                    { 472, "Chris Thomas" },
                    { 473, "Jack Smith" },
                    { 474, "Jack White" },
                    { 475, "Claire White" },
                    { 476, "Julia Taylor" },
                    { 477, "Dave Thomas" },
                    { 478, "Anna Moore" },
                    { 479, "Dave Anderson" },
                    { 480, "John White" },
                    { 481, "Frank Martin" },
                    { 482, "Julia Martinez" },
                    { 483, "Jack Thomas" },
                    { 484, "Greg Martin" },
                    { 485, "Ben Robinson" },
                    { 486, "Jack Johnson" },
                    { 487, "Beth Taylor" },
                    { 488, "Ian Taylor" },
                    { 489, "Grace Miller" },
                    { 490, "Julia Anderson" },
                    { 491, "Jack Williams" },
                    { 492, "Diane Thomas" },
                    { 493, "John Taylor" },
                    { 494, "Dave Davis" },
                    { 495, "Greg Robinson" },
                    { 496, "John Martin" },
                    { 497, "Jack Wilson" },
                    { 498, "Greg White" },
                    { 499, "Ian Harris" },
                    { 500, "Dave Robinson" },
                    { 501, "Ben Robinson" },
                    { 502, "Anna Williams" },
                    { 503, "John Davis" },
                    { 504, "Jack Harris" },
                    { 505, "Chris Smith" },
                    { 506, "Dave Garcia" },
                    { 507, "Chris Johnson" },
                    { 508, "Dave Garcia" },
                    { 509, "Jack Brown" },
                    { 510, "Dave Thomas" },
                    { 511, "Frank Taylor" },
                    { 512, "Dave Johnson" },
                    { 513, "Emily Wilson" },
                    { 514, "Anna Moore" },
                    { 515, "Anna Martin" },
                    { 516, "Ian Williams" },
                    { 517, "Grace Thomas" },
                    { 518, "Frank Davis" },
                    { 519, "Diane Martin" },
                    { 520, "Diane Wilson" },
                    { 521, "Diane Johnson" },
                    { 522, "Dave Davis" },
                    { 523, "Emily Robinson" },
                    { 524, "Diane Miller" },
                    { 525, "John Thompson" },
                    { 526, "Julia Brown" },
                    { 527, "Claire White" },
                    { 528, "Chris Jackson" },
                    { 529, "Julia Martin" },
                    { 530, "Ben Thomas" },
                    { 531, "Ian Harris" },
                    { 532, "Julia Moore" },
                    { 533, "Claire Brown" },
                    { 534, "Jack Robinson" },
                    { 535, "Greg Brown" },
                    { 536, "Ben Smith" },
                    { 537, "Ian Brown" },
                    { 538, "Greg Jackson" },
                    { 539, "Grace Thomas" },
                    { 540, "Dave Harris" },
                    { 541, "John Moore" },
                    { 542, "Chris Brown" },
                    { 543, "John Thomas" },
                    { 544, "Dave Thomas" },
                    { 545, "Emily Miller" },
                    { 546, "Julia Martin" },
                    { 547, "Greg Martinez" },
                    { 548, "Anna Thomas" },
                    { 549, "Grace Smith" },
                    { 550, "Grace Martin" },
                    { 551, "Frank Taylor" },
                    { 552, "Grace Harris" },
                    { 553, "Dave White" },
                    { 554, "Frank Martin" },
                    { 555, "Ian Garcia" },
                    { 556, "Greg Johnson" },
                    { 557, "Julia Miller" },
                    { 558, "Julia Thompson" },
                    { 559, "Chris Harris" },
                    { 560, "Beth Robinson" },
                    { 561, "Julia Williams" },
                    { 562, "Ian Garcia" },
                    { 563, "Grace Miller" },
                    { 564, "Greg Miller" },
                    { 565, "Ben Taylor" },
                    { 566, "Jack Jackson" },
                    { 567, "Claire Garcia" },
                    { 568, "Frank Wilson" },
                    { 569, "Frank Smith" },
                    { 570, "Grace Davis" },
                    { 571, "Ian Brown" },
                    { 572, "John Robinson" },
                    { 573, "Julia Jackson" },
                    { 574, "Anna Moore" },
                    { 575, "Emily Anderson" },
                    { 576, "Emily Taylor" },
                    { 577, "Beth Miller" },
                    { 578, "Frank White" },
                    { 579, "Jack Wilson" },
                    { 580, "Anna Miller" },
                    { 581, "Beth Davis" },
                    { 582, "Grace Taylor" },
                    { 583, "Chris White" },
                    { 584, "Anna Anderson" },
                    { 585, "Diane Miller" },
                    { 586, "Chris Harris" },
                    { 587, "Beth Martinez" },
                    { 588, "Dave Harris" },
                    { 589, "Chris Garcia" },
                    { 590, "Claire Smith" },
                    { 591, "Diane Moore" },
                    { 592, "Greg Johnson" },
                    { 593, "Jack White" },
                    { 594, "Grace Williams" },
                    { 595, "Emily Moore" },
                    { 596, "Frank Brown" },
                    { 597, "Emily Smith" },
                    { 598, "Ian Martin" },
                    { 599, "Beth Martin" },
                    { 600, "Ben Smith" },
                    { 601, "Chris Brown" },
                    { 602, "Claire Moore" },
                    { 603, "Chris Williams" },
                    { 604, "Ian Jackson" },
                    { 605, "Ian Martin" },
                    { 606, "Frank Thompson" },
                    { 607, "Julia Williams" },
                    { 608, "Emily Jackson" },
                    { 609, "Anna Johnson" },
                    { 610, "Dave Wilson" },
                    { 611, "Greg Wilson" },
                    { 612, "Julia Garcia" },
                    { 613, "Ian Anderson" },
                    { 614, "Dave Jackson" },
                    { 615, "Grace Martin" },
                    { 616, "Anna Garcia" },
                    { 617, "Diane Taylor" },
                    { 618, "John Martinez" },
                    { 619, "Julia Williams" },
                    { 620, "Chris Harris" },
                    { 621, "Diane Williams" },
                    { 622, "Ian Garcia" },
                    { 623, "Diane Martinez" },
                    { 624, "Grace Smith" },
                    { 625, "John Thomas" },
                    { 626, "Ian White" },
                    { 627, "Ben Wilson" },
                    { 628, "Beth Thomas" },
                    { 629, "Chris Martinez" },
                    { 630, "Dave Williams" },
                    { 631, "Emily Thomas" },
                    { 632, "Emily Miller" },
                    { 633, "Dave Davis" },
                    { 634, "Anna Williams" },
                    { 635, "Emily White" },
                    { 636, "Chris Thompson" },
                    { 637, "Julia Martin" },
                    { 638, "Diane Davis" },
                    { 639, "Dave Robinson" },
                    { 640, "Ben Martinez" },
                    { 641, "Ian Johnson" },
                    { 642, "Julia Martin" },
                    { 643, "Jack Thomas" },
                    { 644, "Beth Taylor" },
                    { 645, "Claire Wilson" },
                    { 646, "Beth Moore" },
                    { 647, "Ian Thomas" },
                    { 648, "John Martin" },
                    { 649, "Claire Thomas" },
                    { 650, "Greg Anderson" },
                    { 651, "Diane Moore" },
                    { 652, "Claire Moore" },
                    { 653, "Emily Williams" },
                    { 654, "John Wilson" },
                    { 655, "John Moore" },
                    { 656, "Julia Johnson" },
                    { 657, "Frank Jackson" },
                    { 658, "John Smith" },
                    { 659, "Ian Taylor" },
                    { 660, "Ian Martin" },
                    { 661, "Jack Garcia" },
                    { 662, "Chris Williams" },
                    { 663, "Diane Smith" },
                    { 664, "Jack Thomas" },
                    { 665, "Grace Garcia" },
                    { 666, "Chris Moore" },
                    { 667, "Jack Martin" },
                    { 668, "Greg Martinez" },
                    { 669, "Emily Moore" },
                    { 670, "Anna Miller" },
                    { 671, "Frank Garcia" },
                    { 672, "Frank Moore" },
                    { 673, "Chris Wilson" },
                    { 674, "Greg Garcia" },
                    { 675, "Beth Thomas" },
                    { 676, "John Brown" },
                    { 677, "Anna Moore" },
                    { 678, "Julia Brown" },
                    { 679, "Dave White" },
                    { 680, "Grace Brown" },
                    { 681, "Jack Thomas" },
                    { 682, "Beth Anderson" },
                    { 683, "Ben Martinez" },
                    { 684, "Greg Martinez" },
                    { 685, "Anna Martin" },
                    { 686, "Julia Wilson" },
                    { 687, "Diane Brown" },
                    { 688, "Diane Garcia" },
                    { 689, "Beth Williams" },
                    { 690, "Jack Robinson" },
                    { 691, "Julia Taylor" },
                    { 692, "Jack Harris" },
                    { 693, "Grace Smith" },
                    { 694, "Anna Martin" },
                    { 695, "Greg Anderson" },
                    { 696, "Chris Harris" },
                    { 697, "Anna Brown" },
                    { 698, "Frank Smith" },
                    { 699, "Emily Martin" },
                    { 700, "Dave White" },
                    { 701, "Frank White" },
                    { 702, "Anna Martinez" },
                    { 703, "Beth Smith" },
                    { 704, "Chris Martinez" },
                    { 705, "Chris Jackson" },
                    { 706, "Jack Jackson" },
                    { 707, "Diane Moore" },
                    { 708, "Jack Miller" },
                    { 709, "Emily Robinson" },
                    { 710, "Emily Anderson" },
                    { 711, "Emily Johnson" },
                    { 712, "Beth White" },
                    { 713, "Chris Miller" },
                    { 714, "Greg Moore" },
                    { 715, "Dave Wilson" },
                    { 716, "Grace Martinez" },
                    { 717, "John Wilson" },
                    { 718, "Grace Jackson" },
                    { 719, "Claire Taylor" },
                    { 720, "Emily White" },
                    { 721, "Ben Davis" },
                    { 722, "Jack Robinson" },
                    { 723, "Beth Davis" },
                    { 724, "Claire Moore" },
                    { 725, "Ian Miller" },
                    { 726, "Beth Williams" },
                    { 727, "Anna Robinson" },
                    { 728, "Claire Harris" },
                    { 729, "Emily Thomas" },
                    { 730, "Anna Johnson" },
                    { 731, "Beth Taylor" },
                    { 732, "Julia Moore" },
                    { 733, "Frank Taylor" },
                    { 734, "Julia Taylor" },
                    { 735, "Dave Davis" },
                    { 736, "Jack Taylor" },
                    { 737, "Ben Smith" },
                    { 738, "Grace Jackson" },
                    { 739, "Chris Davis" },
                    { 740, "Chris Davis" },
                    { 741, "Jack Garcia" },
                    { 742, "Frank Williams" },
                    { 743, "Dave Wilson" },
                    { 744, "Diane Brown" },
                    { 745, "Beth Thomas" },
                    { 746, "Frank Wilson" },
                    { 747, "Grace Martinez" },
                    { 748, "Grace Johnson" },
                    { 749, "Anna Miller" },
                    { 750, "Ian Martin" },
                    { 751, "Diane Miller" },
                    { 752, "Chris Wilson" },
                    { 753, "Frank Martinez" },
                    { 754, "Ian Miller" },
                    { 755, "John Taylor" },
                    { 756, "Frank Johnson" },
                    { 757, "Jack Jackson" },
                    { 758, "Claire Johnson" },
                    { 759, "Jack White" },
                    { 760, "Ian Harris" },
                    { 761, "Grace Anderson" },
                    { 762, "Frank Thomas" },
                    { 763, "Dave Anderson" },
                    { 764, "Grace Miller" },
                    { 765, "Chris Miller" },
                    { 766, "Greg Davis" },
                    { 767, "Frank Robinson" },
                    { 768, "Emily Brown" },
                    { 769, "Jack Harris" },
                    { 770, "Ben Smith" },
                    { 771, "Ian Davis" },
                    { 772, "Grace Martin" },
                    { 773, "Greg Moore" },
                    { 774, "Grace Thompson" },
                    { 775, "Frank Moore" },
                    { 776, "Ben Williams" },
                    { 777, "Diane Thompson" },
                    { 778, "Claire Jackson" },
                    { 779, "Greg Davis" },
                    { 780, "Grace Robinson" },
                    { 781, "Chris Miller" },
                    { 782, "Greg Taylor" },
                    { 783, "Greg Miller" },
                    { 784, "John Moore" },
                    { 785, "Diane Jackson" },
                    { 786, "Julia Thompson" },
                    { 787, "Ben Davis" },
                    { 788, "Diane Taylor" },
                    { 789, "Ian Thomas" },
                    { 790, "Jack Moore" },
                    { 791, "Grace Moore" },
                    { 792, "Emily Taylor" },
                    { 793, "Diane Thomas" },
                    { 794, "Anna Miller" },
                    { 795, "Chris Johnson" },
                    { 796, "Emily Robinson" },
                    { 797, "Diane Martinez" },
                    { 798, "Julia Davis" },
                    { 799, "Dave Garcia" },
                    { 800, "Diane Brown" },
                    { 801, "Dave Davis" },
                    { 802, "Anna Davis" },
                    { 803, "Jack Wilson" },
                    { 804, "Jack Smith" },
                    { 805, "Beth White" },
                    { 806, "Julia Moore" },
                    { 807, "Greg Moore" },
                    { 808, "Ian Brown" },
                    { 809, "Jack Wilson" },
                    { 810, "Chris Johnson" },
                    { 811, "Beth Brown" },
                    { 812, "Greg Miller" },
                    { 813, "Diane Moore" },
                    { 814, "Greg Moore" },
                    { 815, "Ian Thomas" },
                    { 816, "Chris Martinez" },
                    { 817, "Beth Robinson" },
                    { 818, "Emily Brown" },
                    { 819, "Julia Taylor" },
                    { 820, "Claire Brown" },
                    { 821, "Julia Williams" },
                    { 822, "Grace Anderson" },
                    { 823, "Greg Moore" },
                    { 824, "Emily Brown" },
                    { 825, "Beth Martinez" },
                    { 826, "Grace Davis" },
                    { 827, "Grace Thompson" },
                    { 828, "Ben Brown" },
                    { 829, "Greg Anderson" },
                    { 830, "Emily Thomas" },
                    { 831, "Greg Williams" },
                    { 832, "Greg White" },
                    { 833, "Diane Moore" },
                    { 834, "Frank Moore" },
                    { 835, "Diane Harris" },
                    { 836, "John Miller" },
                    { 837, "Frank Smith" },
                    { 838, "Greg Martin" },
                    { 839, "Ian Smith" },
                    { 840, "Greg Garcia" },
                    { 841, "Dave Jackson" },
                    { 842, "Julia Harris" },
                    { 843, "Ian Martinez" },
                    { 844, "Claire Taylor" },
                    { 845, "Beth Johnson" },
                    { 846, "Frank Garcia" },
                    { 847, "Diane Davis" },
                    { 848, "Frank Moore" },
                    { 849, "Julia Taylor" },
                    { 850, "Claire Williams" },
                    { 851, "John Harris" },
                    { 852, "Beth Taylor" },
                    { 853, "Frank Johnson" },
                    { 854, "Ian Moore" },
                    { 855, "Anna Garcia" },
                    { 856, "Ian Brown" },
                    { 857, "Diane Williams" },
                    { 858, "Frank Thompson" },
                    { 859, "John Jackson" },
                    { 860, "Greg Anderson" },
                    { 861, "Diane Martinez" },
                    { 862, "Greg Garcia" },
                    { 863, "Greg Johnson" },
                    { 864, "Anna Brown" },
                    { 865, "Julia Anderson" },
                    { 866, "Grace Wilson" },
                    { 867, "Ian Miller" },
                    { 868, "Ian White" },
                    { 869, "Anna Garcia" },
                    { 870, "Grace Harris" },
                    { 871, "Ben Johnson" },
                    { 872, "Anna Brown" },
                    { 873, "Jack Miller" },
                    { 874, "Anna Moore" },
                    { 875, "John Miller" },
                    { 876, "Grace White" },
                    { 877, "Frank Brown" },
                    { 878, "Chris Martinez" },
                    { 879, "Frank Johnson" },
                    { 880, "Dave Williams" },
                    { 881, "Ben Thomas" },
                    { 882, "Dave Miller" },
                    { 883, "Ben Robinson" },
                    { 884, "Diane Wilson" },
                    { 885, "Ben Thomas" },
                    { 886, "Chris Martin" },
                    { 887, "Greg Taylor" },
                    { 888, "Claire Johnson" },
                    { 889, "John Miller" },
                    { 890, "Frank Taylor" },
                    { 891, "Emily Taylor" },
                    { 892, "Chris Robinson" },
                    { 893, "Ian White" },
                    { 894, "John Martin" },
                    { 895, "Beth Miller" },
                    { 896, "Diane Martin" },
                    { 897, "Julia Davis" },
                    { 898, "Dave Wilson" },
                    { 899, "Frank Moore" },
                    { 900, "Emily Smith" },
                    { 901, "Diane Jackson" },
                    { 902, "Anna Martinez" },
                    { 903, "Chris Harris" },
                    { 904, "Anna Moore" },
                    { 905, "Dave Jackson" },
                    { 906, "Greg Thomas" },
                    { 907, "Beth Moore" },
                    { 908, "Beth Thompson" },
                    { 909, "Emily Anderson" },
                    { 910, "Frank Robinson" },
                    { 911, "Beth Smith" },
                    { 912, "Julia Thompson" },
                    { 913, "John Miller" },
                    { 914, "Anna Davis" },
                    { 915, "Emily Miller" },
                    { 916, "Chris Harris" },
                    { 917, "Beth Davis" },
                    { 918, "John Wilson" },
                    { 919, "Grace Garcia" },
                    { 920, "Diane Anderson" },
                    { 921, "Ben White" },
                    { 922, "Frank Harris" },
                    { 923, "Beth Jackson" },
                    { 924, "Anna Williams" },
                    { 925, "Jack Davis" },
                    { 926, "Chris Miller" },
                    { 927, "Julia White" },
                    { 928, "Frank Thomas" },
                    { 929, "Emily Thompson" },
                    { 930, "Julia Thompson" },
                    { 931, "Grace Anderson" },
                    { 932, "Greg Martin" },
                    { 933, "John Martin" },
                    { 934, "Chris Moore" },
                    { 935, "Ian Smith" },
                    { 936, "Jack Harris" },
                    { 937, "Ben Harris" },
                    { 938, "Grace Jackson" },
                    { 939, "Chris Thomas" },
                    { 940, "Claire Garcia" },
                    { 941, "Greg Brown" },
                    { 942, "Diane Davis" },
                    { 943, "Chris Harris" },
                    { 944, "Claire White" },
                    { 945, "Jack Thompson" },
                    { 946, "John Taylor" },
                    { 947, "Julia Smith" },
                    { 948, "Dave Martin" },
                    { 949, "Emily Thompson" },
                    { 950, "Frank Robinson" },
                    { 951, "Greg Moore" },
                    { 952, "Claire Martinez" },
                    { 953, "Emily Johnson" },
                    { 954, "Claire Miller" },
                    { 955, "Claire Harris" },
                    { 956, "Emily Thompson" },
                    { 957, "Claire Harris" },
                    { 958, "Ben Williams" },
                    { 959, "Chris Brown" },
                    { 960, "Emily Smith" },
                    { 961, "Frank Brown" },
                    { 962, "Chris Brown" },
                    { 963, "Greg Anderson" },
                    { 964, "Ian Davis" },
                    { 965, "Diane Davis" },
                    { 966, "John Anderson" },
                    { 967, "Anna Jackson" },
                    { 968, "John Robinson" },
                    { 969, "Greg Davis" },
                    { 970, "Julia Harris" },
                    { 971, "Beth Jackson" },
                    { 972, "Beth Jackson" },
                    { 973, "Jack Davis" },
                    { 974, "Ben Thomas" },
                    { 975, "Dave Brown" },
                    { 976, "Chris Harris" },
                    { 977, "John Smith" },
                    { 978, "Frank Thompson" },
                    { 979, "Frank Davis" },
                    { 980, "Jack White" },
                    { 981, "Anna Williams" },
                    { 982, "Ian Robinson" },
                    { 983, "Diane Garcia" },
                    { 984, "Grace White" },
                    { 985, "Emily Harris" },
                    { 986, "Emily Brown" },
                    { 987, "Julia Anderson" },
                    { 988, "Beth Taylor" },
                    { 989, "Greg Martinez" },
                    { 990, "Dave White" },
                    { 991, "Ben Wilson" },
                    { 992, "John Williams" },
                    { 993, "Ben Taylor" },
                    { 994, "Beth Thompson" },
                    { 995, "Grace Moore" },
                    { 996, "Diane Harris" },
                    { 997, "Anna Anderson" },
                    { 998, "Frank Moore" },
                    { 999, "Diane Harris" },
                    { 1000, "Ben Davis" }
                });

            migrationBuilder.InsertData(
                table: "appointments",
                columns: new[] { "id", "appointment_time", "doctor_id", "patient_id" },
                values: new object[,]
                {
                    { 1, new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc), 7, 864 },
                    { 2, new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc), 3, 893 },
                    { 3, new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Utc), 3, 208 },
                    { 4, new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc), 3, 573 },
                    { 5, new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc), 13, 707 },
                    { 6, new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc), 10, 606 },
                    { 7, new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc), 6, 940 },
                    { 8, new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc), 4, 715 },
                    { 9, new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc), 15, 124 },
                    { 10, new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc), 13, 448 },
                    { 11, new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc), 13, 89 },
                    { 12, new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc), 4, 457 },
                    { 13, new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc), 1, 113 },
                    { 14, new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc), 4, 344 },
                    { 15, new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc), 9, 708 },
                    { 16, new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc), 5, 121 },
                    { 17, new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Utc), 4, 458 },
                    { 18, new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc), 7, 619 },
                    { 19, new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc), 15, 629 },
                    { 20, new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc), 2, 202 },
                    { 21, new DateTime(2025, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc), 15, 595 },
                    { 22, new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc), 13, 401 },
                    { 23, new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc), 4, 173 },
                    { 24, new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc), 2, 188 },
                    { 25, new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc), 1, 565 },
                    { 26, new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc), 5, 242 },
                    { 27, new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Utc), 9, 30 },
                    { 28, new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Utc), 1, 516 },
                    { 29, new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc), 13, 53 },
                    { 30, new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc), 12, 106 },
                    { 31, new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc), 7, 537 },
                    { 32, new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc), 8, 862 },
                    { 33, new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc), 9, 713 },
                    { 34, new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Utc), 14, 658 },
                    { 35, new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc), 2, 987 },
                    { 36, new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc), 4, 399 },
                    { 37, new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc), 11, 89 },
                    { 38, new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc), 7, 524 },
                    { 39, new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc), 7, 786 },
                    { 40, new DateTime(2024, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc), 10, 610 },
                    { 41, new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Utc), 13, 254 },
                    { 42, new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc), 4, 102 },
                    { 43, new DateTime(2024, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc), 11, 506 },
                    { 44, new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc), 9, 873 },
                    { 45, new DateTime(2024, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc), 1, 172 },
                    { 46, new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), 10, 969 },
                    { 47, new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc), 1, 236 },
                    { 48, new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc), 9, 856 },
                    { 49, new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc), 12, 981 },
                    { 50, new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc), 4, 79 },
                    { 51, new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc), 1, 104 },
                    { 52, new DateTime(2025, 12, 18, 0, 0, 0, 0, DateTimeKind.Utc), 12, 197 },
                    { 53, new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc), 8, 275 },
                    { 54, new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc), 15, 468 },
                    { 55, new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc), 12, 558 },
                    { 56, new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc), 13, 126 },
                    { 57, new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc), 10, 827 },
                    { 58, new DateTime(2024, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc), 10, 499 },
                    { 59, new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc), 6, 560 },
                    { 60, new DateTime(2025, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc), 5, 324 },
                    { 61, new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc), 14, 495 },
                    { 62, new DateTime(2025, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), 1, 988 },
                    { 63, new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc), 12, 631 },
                    { 64, new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Utc), 5, 801 },
                    { 65, new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc), 9, 28 },
                    { 66, new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Utc), 12, 728 },
                    { 67, new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc), 13, 396 },
                    { 68, new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc), 11, 683 },
                    { 69, new DateTime(2024, 7, 28, 0, 0, 0, 0, DateTimeKind.Utc), 2, 21 },
                    { 70, new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Utc), 15, 455 },
                    { 71, new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Utc), 15, 369 },
                    { 72, new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc), 9, 474 },
                    { 73, new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc), 12, 186 },
                    { 74, new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc), 2, 237 },
                    { 75, new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc), 6, 854 },
                    { 76, new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc), 12, 596 },
                    { 77, new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc), 15, 883 },
                    { 78, new DateTime(2025, 9, 14, 0, 0, 0, 0, DateTimeKind.Utc), 8, 503 },
                    { 79, new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc), 5, 43 },
                    { 80, new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc), 12, 953 },
                    { 81, new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc), 13, 707 },
                    { 82, new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Utc), 11, 655 },
                    { 83, new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc), 6, 425 },
                    { 84, new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc), 8, 735 },
                    { 85, new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc), 3, 354 },
                    { 86, new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc), 9, 199 },
                    { 87, new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc), 5, 946 },
                    { 88, new DateTime(2025, 12, 16, 0, 0, 0, 0, DateTimeKind.Utc), 8, 748 },
                    { 89, new DateTime(2025, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc), 9, 327 },
                    { 90, new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc), 4, 621 },
                    { 91, new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc), 12, 192 },
                    { 92, new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc), 12, 969 },
                    { 93, new DateTime(2024, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), 6, 460 },
                    { 94, new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc), 9, 394 },
                    { 95, new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc), 12, 964 },
                    { 96, new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc), 13, 442 },
                    { 97, new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc), 6, 985 },
                    { 98, new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Utc), 8, 738 },
                    { 99, new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc), 5, 859 },
                    { 100, new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc), 4, 309 },
                    { 101, new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc), 11, 318 },
                    { 102, new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc), 9, 665 },
                    { 103, new DateTime(2025, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc), 15, 957 },
                    { 104, new DateTime(2024, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc), 12, 387 },
                    { 105, new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc), 7, 193 },
                    { 106, new DateTime(2025, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc), 6, 785 },
                    { 107, new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc), 1, 233 },
                    { 108, new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc), 1, 130 },
                    { 109, new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc), 13, 87 },
                    { 110, new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc), 11, 800 },
                    { 111, new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Utc), 6, 657 },
                    { 112, new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc), 7, 844 },
                    { 113, new DateTime(2025, 12, 23, 0, 0, 0, 0, DateTimeKind.Utc), 4, 686 },
                    { 114, new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc), 4, 277 },
                    { 115, new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc), 3, 421 },
                    { 116, new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc), 11, 228 },
                    { 117, new DateTime(2024, 8, 19, 0, 0, 0, 0, DateTimeKind.Utc), 14, 217 },
                    { 118, new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc), 15, 763 },
                    { 119, new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc), 3, 259 },
                    { 120, new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc), 8, 464 },
                    { 121, new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc), 11, 790 },
                    { 122, new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc), 9, 885 },
                    { 123, new DateTime(2025, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc), 13, 17 },
                    { 124, new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc), 2, 901 },
                    { 125, new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc), 13, 718 },
                    { 126, new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc), 2, 524 },
                    { 127, new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc), 2, 481 },
                    { 128, new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc), 14, 141 },
                    { 129, new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc), 13, 779 },
                    { 130, new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc), 10, 481 },
                    { 131, new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc), 13, 117 },
                    { 132, new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc), 14, 837 },
                    { 133, new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc), 7, 391 },
                    { 134, new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc), 2, 66 },
                    { 135, new DateTime(2024, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc), 1, 889 },
                    { 136, new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc), 4, 96 },
                    { 137, new DateTime(2024, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc), 15, 298 },
                    { 138, new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc), 7, 567 },
                    { 139, new DateTime(2024, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc), 14, 485 },
                    { 140, new DateTime(2025, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc), 3, 645 },
                    { 141, new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Utc), 10, 273 },
                    { 142, new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc), 3, 991 },
                    { 143, new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc), 6, 949 },
                    { 144, new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc), 5, 621 },
                    { 145, new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc), 12, 931 },
                    { 146, new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc), 7, 53 },
                    { 147, new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Utc), 12, 516 },
                    { 148, new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc), 13, 319 },
                    { 149, new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc), 13, 847 },
                    { 150, new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc), 5, 204 },
                    { 151, new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc), 8, 417 },
                    { 152, new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc), 12, 341 },
                    { 153, new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc), 8, 132 },
                    { 154, new DateTime(2024, 9, 29, 0, 0, 0, 0, DateTimeKind.Utc), 13, 295 },
                    { 155, new DateTime(2025, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc), 14, 846 },
                    { 156, new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc), 11, 909 },
                    { 157, new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc), 8, 555 },
                    { 158, new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Utc), 14, 212 },
                    { 159, new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Utc), 10, 747 },
                    { 160, new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc), 7, 203 },
                    { 161, new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Utc), 10, 974 },
                    { 162, new DateTime(2024, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc), 1, 767 },
                    { 163, new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc), 11, 874 },
                    { 164, new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc), 3, 62 },
                    { 165, new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc), 5, 110 },
                    { 166, new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Utc), 7, 239 },
                    { 167, new DateTime(2024, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc), 3, 729 },
                    { 168, new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc), 13, 486 },
                    { 169, new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Utc), 15, 644 },
                    { 170, new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc), 1, 9 },
                    { 171, new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc), 9, 288 },
                    { 172, new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc), 4, 518 },
                    { 173, new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc), 2, 768 },
                    { 174, new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Utc), 15, 303 },
                    { 175, new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Utc), 13, 87 },
                    { 176, new DateTime(2025, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc), 4, 655 },
                    { 177, new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Utc), 13, 776 },
                    { 178, new DateTime(2024, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc), 2, 147 },
                    { 179, new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc), 14, 444 },
                    { 180, new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Utc), 1, 164 },
                    { 181, new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Utc), 4, 677 },
                    { 182, new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc), 15, 95 },
                    { 183, new DateTime(2025, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc), 8, 53 },
                    { 184, new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc), 4, 184 },
                    { 185, new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc), 1, 616 },
                    { 186, new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc), 1, 628 },
                    { 187, new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Utc), 9, 282 },
                    { 188, new DateTime(2024, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc), 7, 915 },
                    { 189, new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc), 9, 897 },
                    { 190, new DateTime(2024, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc), 8, 383 },
                    { 191, new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Utc), 11, 161 },
                    { 192, new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc), 15, 496 },
                    { 193, new DateTime(2024, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc), 1, 221 },
                    { 194, new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc), 9, 695 },
                    { 195, new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc), 13, 276 },
                    { 196, new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Utc), 6, 753 },
                    { 197, new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc), 6, 420 },
                    { 198, new DateTime(2024, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc), 6, 777 },
                    { 199, new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Utc), 4, 972 },
                    { 200, new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc), 5, 550 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_appointments_doctor_id",
                table: "appointments",
                column: "doctor_id");

            migrationBuilder.CreateIndex(
                name: "IX_appointments_patient_id",
                table: "appointments",
                column: "patient_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "appointments");

            migrationBuilder.DropTable(
                name: "doctors");

            migrationBuilder.DropTable(
                name: "patients");
        }
    }
}
