// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240910114030_twelthMigration")]
    partial class twelthMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctorId");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patientId");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("prescription_id");

                    b.Property<DateTime>("Booking")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("type")
                        .HasColumnType("integer");

                    b.HasKey("DoctorId", "PatientId", "PrescriptionId");

                    b.ToTable("appointments");

                    b.HasData(
                        new
                        {
                            DoctorId = 9,
                            PatientId = 1,
                            PrescriptionId = 1,
                            Booking = new DateTime(2024, 12, 8, 5, 22, 15, 237, DateTimeKind.Utc).AddTicks(7064),
                            Id = 1,
                            type = 0
                        },
                        new
                        {
                            DoctorId = 5,
                            PatientId = 2,
                            PrescriptionId = 2,
                            Booking = new DateTime(2025, 8, 29, 14, 22, 57, 237, DateTimeKind.Utc).AddTicks(7183),
                            Id = 2,
                            type = 1
                        },
                        new
                        {
                            DoctorId = 9,
                            PatientId = 3,
                            PrescriptionId = 3,
                            Booking = new DateTime(2025, 7, 5, 2, 19, 34, 237, DateTimeKind.Utc).AddTicks(7212),
                            Id = 3,
                            type = 0
                        },
                        new
                        {
                            DoctorId = 4,
                            PatientId = 4,
                            PrescriptionId = 4,
                            Booking = new DateTime(2025, 7, 28, 10, 27, 46, 237, DateTimeKind.Utc).AddTicks(7222),
                            Id = 4,
                            type = 1
                        },
                        new
                        {
                            DoctorId = 10,
                            PatientId = 5,
                            PrescriptionId = 5,
                            Booking = new DateTime(2024, 10, 30, 16, 51, 20, 237, DateTimeKind.Utc).AddTicks(7253),
                            Id = 5,
                            type = 0
                        },
                        new
                        {
                            DoctorId = 5,
                            PatientId = 6,
                            PrescriptionId = 6,
                            Booking = new DateTime(2025, 6, 13, 3, 19, 52, 237, DateTimeKind.Utc).AddTicks(7259),
                            Id = 6,
                            type = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            PatientId = 7,
                            PrescriptionId = 7,
                            Booking = new DateTime(2024, 9, 22, 8, 42, 41, 237, DateTimeKind.Utc).AddTicks(7264),
                            Id = 7,
                            type = 0
                        },
                        new
                        {
                            DoctorId = 10,
                            PatientId = 8,
                            PrescriptionId = 8,
                            Booking = new DateTime(2025, 1, 6, 3, 57, 2, 237, DateTimeKind.Utc).AddTicks(7268),
                            Id = 8,
                            type = 0
                        },
                        new
                        {
                            DoctorId = 3,
                            PatientId = 9,
                            PrescriptionId = 9,
                            Booking = new DateTime(2024, 11, 13, 15, 6, 23, 237, DateTimeKind.Utc).AddTicks(7272),
                            Id = 9,
                            type = 1
                        },
                        new
                        {
                            DoctorId = 4,
                            PatientId = 10,
                            PrescriptionId = 10,
                            Booking = new DateTime(2025, 7, 30, 20, 45, 34, 237, DateTimeKind.Utc).AddTicks(7277),
                            Id = 10,
                            type = 1
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.HasKey("Id");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Neo Andersson"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Neo Schwarzenegger"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Donald Andersson"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Neo Sandler"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Mickey Presley"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Charles Xavier"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Arnold Presley"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Felix Winfrey"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Barack Mathiasson"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.ToTable("medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instruction = "Chew on it for 3 hours.",
                            Name = "Blazing Laxatives",
                            Quantity = 36
                        },
                        new
                        {
                            Id = 2,
                            Instruction = "Mix with chicken noodle soup.",
                            Name = "Crazy Blue Pills",
                            Quantity = 85
                        },
                        new
                        {
                            Id = 3,
                            Instruction = "Disolve into drink of your choice.",
                            Name = "Bad Drugs",
                            Quantity = 73
                        },
                        new
                        {
                            Id = 4,
                            Instruction = "Insert into rectum.",
                            Name = "Not Xanax",
                            Quantity = 75
                        },
                        new
                        {
                            Id = 5,
                            Instruction = "Mix with chicken noodle soup.",
                            Name = "Ultra Mushrooms",
                            Quantity = 66
                        },
                        new
                        {
                            Id = 6,
                            Instruction = "Hide in cabinet and let the placebo effect do it's job.",
                            Name = "Crazy Aspirin",
                            Quantity = 80
                        },
                        new
                        {
                            Id = 7,
                            Instruction = "Mix with chicken noodle soup.",
                            Name = "Yummy Xanax",
                            Quantity = 74
                        },
                        new
                        {
                            Id = 8,
                            Instruction = "Mix with chicken noodle soup.",
                            Name = "Blazing Heroin",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 9,
                            Instruction = "Put in coworker's food.",
                            Name = "Blazing Xanax",
                            Quantity = 93
                        },
                        new
                        {
                            Id = 10,
                            Instruction = "Put in coworker's food.",
                            Name = "Not Potion",
                            Quantity = 93
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.HasKey("Id");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Donald Mouse"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Charles Schwarzenegger"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Donald Xavier"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Neo Presley"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Adam Duck"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Kate Winslow"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Ragnar Mouse"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Neo Winfrey"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Barack Winfrey"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.PrescriptionMedicine", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("prescription_id");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer")
                        .HasColumnName("medicine_id");

                    b.HasKey("PrescriptionId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("prescription_medicines");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 10,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 9,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 10,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 9,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 10
                        },
                        new
                        {
                            PrescriptionId = 10,
                            MedicineId = 10
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 10
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.PrescriptionMedicine", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workshop.wwwapi.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionMedicines");
                });
#pragma warning restore 612, 618
        }
    }
}
