// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240205150843_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Appointment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appointment_time");

                    b.Property<int>("DoctorID")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("appointments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AppointmentTime = new DateTime(2025, 3, 31, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 22
                        },
                        new
                        {
                            ID = 2,
                            AppointmentTime = new DateTime(2025, 12, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 2,
                            PatientID = 112
                        },
                        new
                        {
                            ID = 3,
                            AppointmentTime = new DateTime(2024, 7, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 18,
                            PatientID = 74
                        },
                        new
                        {
                            ID = 4,
                            AppointmentTime = new DateTime(2024, 2, 18, 17, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 4,
                            PatientID = 83
                        },
                        new
                        {
                            ID = 5,
                            AppointmentTime = new DateTime(2025, 4, 21, 18, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 89
                        },
                        new
                        {
                            ID = 6,
                            AppointmentTime = new DateTime(2024, 10, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 9,
                            PatientID = 200
                        },
                        new
                        {
                            ID = 7,
                            AppointmentTime = new DateTime(2025, 5, 29, 7, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 5,
                            PatientID = 133
                        },
                        new
                        {
                            ID = 8,
                            AppointmentTime = new DateTime(2025, 2, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 20,
                            PatientID = 9
                        },
                        new
                        {
                            ID = 9,
                            AppointmentTime = new DateTime(2024, 3, 27, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 134
                        },
                        new
                        {
                            ID = 10,
                            AppointmentTime = new DateTime(2024, 11, 25, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 122
                        },
                        new
                        {
                            ID = 11,
                            AppointmentTime = new DateTime(2025, 11, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 105
                        },
                        new
                        {
                            ID = 12,
                            AppointmentTime = new DateTime(2025, 10, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 11
                        },
                        new
                        {
                            ID = 13,
                            AppointmentTime = new DateTime(2024, 7, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 169
                        },
                        new
                        {
                            ID = 14,
                            AppointmentTime = new DateTime(2025, 4, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 18,
                            PatientID = 179
                        },
                        new
                        {
                            ID = 15,
                            AppointmentTime = new DateTime(2025, 1, 21, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 185
                        },
                        new
                        {
                            ID = 16,
                            AppointmentTime = new DateTime(2024, 2, 23, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 17,
                            PatientID = 29
                        },
                        new
                        {
                            ID = 17,
                            AppointmentTime = new DateTime(2025, 10, 10, 18, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 133
                        },
                        new
                        {
                            ID = 18,
                            AppointmentTime = new DateTime(2024, 6, 16, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 11,
                            PatientID = 32
                        },
                        new
                        {
                            ID = 19,
                            AppointmentTime = new DateTime(2025, 12, 29, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 92
                        },
                        new
                        {
                            ID = 20,
                            AppointmentTime = new DateTime(2024, 4, 19, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 133
                        },
                        new
                        {
                            ID = 21,
                            AppointmentTime = new DateTime(2025, 5, 5, 17, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 84
                        },
                        new
                        {
                            ID = 22,
                            AppointmentTime = new DateTime(2024, 5, 12, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 14,
                            PatientID = 21
                        },
                        new
                        {
                            ID = 23,
                            AppointmentTime = new DateTime(2024, 8, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 97
                        },
                        new
                        {
                            ID = 24,
                            AppointmentTime = new DateTime(2024, 2, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 67
                        },
                        new
                        {
                            ID = 25,
                            AppointmentTime = new DateTime(2024, 5, 24, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 11,
                            PatientID = 177
                        },
                        new
                        {
                            ID = 26,
                            AppointmentTime = new DateTime(2024, 3, 22, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 2,
                            PatientID = 52
                        },
                        new
                        {
                            ID = 27,
                            AppointmentTime = new DateTime(2024, 12, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 11,
                            PatientID = 100
                        },
                        new
                        {
                            ID = 28,
                            AppointmentTime = new DateTime(2024, 12, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 20,
                            PatientID = 175
                        },
                        new
                        {
                            ID = 29,
                            AppointmentTime = new DateTime(2024, 11, 28, 7, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 16,
                            PatientID = 18
                        },
                        new
                        {
                            ID = 30,
                            AppointmentTime = new DateTime(2025, 10, 11, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 2,
                            PatientID = 106
                        },
                        new
                        {
                            ID = 31,
                            AppointmentTime = new DateTime(2024, 2, 12, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 162
                        },
                        new
                        {
                            ID = 32,
                            AppointmentTime = new DateTime(2025, 10, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 2,
                            PatientID = 176
                        },
                        new
                        {
                            ID = 33,
                            AppointmentTime = new DateTime(2024, 10, 14, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 71
                        },
                        new
                        {
                            ID = 34,
                            AppointmentTime = new DateTime(2024, 6, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 110
                        },
                        new
                        {
                            ID = 35,
                            AppointmentTime = new DateTime(2025, 9, 19, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 68
                        },
                        new
                        {
                            ID = 36,
                            AppointmentTime = new DateTime(2025, 5, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 119
                        },
                        new
                        {
                            ID = 37,
                            AppointmentTime = new DateTime(2025, 4, 3, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 150
                        },
                        new
                        {
                            ID = 38,
                            AppointmentTime = new DateTime(2025, 8, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 35
                        },
                        new
                        {
                            ID = 39,
                            AppointmentTime = new DateTime(2025, 5, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 189
                        },
                        new
                        {
                            ID = 40,
                            AppointmentTime = new DateTime(2024, 4, 7, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 20,
                            PatientID = 71
                        },
                        new
                        {
                            ID = 41,
                            AppointmentTime = new DateTime(2024, 6, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 64
                        },
                        new
                        {
                            ID = 42,
                            AppointmentTime = new DateTime(2024, 11, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 58
                        },
                        new
                        {
                            ID = 43,
                            AppointmentTime = new DateTime(2024, 6, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 110
                        },
                        new
                        {
                            ID = 44,
                            AppointmentTime = new DateTime(2025, 1, 13, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 138
                        },
                        new
                        {
                            ID = 45,
                            AppointmentTime = new DateTime(2025, 3, 18, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 28
                        },
                        new
                        {
                            ID = 46,
                            AppointmentTime = new DateTime(2025, 11, 23, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 177
                        },
                        new
                        {
                            ID = 47,
                            AppointmentTime = new DateTime(2024, 4, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 14,
                            PatientID = 104
                        },
                        new
                        {
                            ID = 48,
                            AppointmentTime = new DateTime(2024, 8, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 120
                        },
                        new
                        {
                            ID = 49,
                            AppointmentTime = new DateTime(2024, 2, 14, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 54
                        },
                        new
                        {
                            ID = 50,
                            AppointmentTime = new DateTime(2024, 7, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 11,
                            PatientID = 31
                        },
                        new
                        {
                            ID = 51,
                            AppointmentTime = new DateTime(2024, 9, 11, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 139
                        },
                        new
                        {
                            ID = 52,
                            AppointmentTime = new DateTime(2025, 12, 21, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 194
                        },
                        new
                        {
                            ID = 53,
                            AppointmentTime = new DateTime(2024, 10, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 155
                        },
                        new
                        {
                            ID = 54,
                            AppointmentTime = new DateTime(2024, 3, 7, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 98
                        },
                        new
                        {
                            ID = 55,
                            AppointmentTime = new DateTime(2025, 12, 6, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 185
                        },
                        new
                        {
                            ID = 56,
                            AppointmentTime = new DateTime(2025, 1, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 18,
                            PatientID = 142
                        },
                        new
                        {
                            ID = 57,
                            AppointmentTime = new DateTime(2024, 7, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 2,
                            PatientID = 168
                        },
                        new
                        {
                            ID = 58,
                            AppointmentTime = new DateTime(2024, 11, 27, 17, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 20,
                            PatientID = 172
                        },
                        new
                        {
                            ID = 59,
                            AppointmentTime = new DateTime(2025, 7, 26, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 136
                        },
                        new
                        {
                            ID = 60,
                            AppointmentTime = new DateTime(2025, 6, 29, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 121
                        },
                        new
                        {
                            ID = 61,
                            AppointmentTime = new DateTime(2024, 1, 26, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 168
                        },
                        new
                        {
                            ID = 62,
                            AppointmentTime = new DateTime(2024, 9, 29, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 159
                        },
                        new
                        {
                            ID = 63,
                            AppointmentTime = new DateTime(2025, 7, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 96
                        },
                        new
                        {
                            ID = 64,
                            AppointmentTime = new DateTime(2024, 5, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 198
                        },
                        new
                        {
                            ID = 65,
                            AppointmentTime = new DateTime(2024, 5, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 1,
                            PatientID = 161
                        },
                        new
                        {
                            ID = 66,
                            AppointmentTime = new DateTime(2024, 4, 11, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 83
                        },
                        new
                        {
                            ID = 67,
                            AppointmentTime = new DateTime(2025, 11, 16, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 140
                        },
                        new
                        {
                            ID = 68,
                            AppointmentTime = new DateTime(2025, 7, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 9,
                            PatientID = 125
                        },
                        new
                        {
                            ID = 69,
                            AppointmentTime = new DateTime(2025, 4, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 16,
                            PatientID = 123
                        },
                        new
                        {
                            ID = 70,
                            AppointmentTime = new DateTime(2024, 5, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 5
                        },
                        new
                        {
                            ID = 71,
                            AppointmentTime = new DateTime(2024, 2, 12, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 27
                        },
                        new
                        {
                            ID = 72,
                            AppointmentTime = new DateTime(2024, 3, 29, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 114
                        },
                        new
                        {
                            ID = 73,
                            AppointmentTime = new DateTime(2024, 7, 2, 19, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 111
                        },
                        new
                        {
                            ID = 74,
                            AppointmentTime = new DateTime(2025, 8, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 26
                        },
                        new
                        {
                            ID = 75,
                            AppointmentTime = new DateTime(2024, 4, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 45
                        },
                        new
                        {
                            ID = 76,
                            AppointmentTime = new DateTime(2025, 7, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 13,
                            PatientID = 146
                        },
                        new
                        {
                            ID = 77,
                            AppointmentTime = new DateTime(2025, 9, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 7
                        },
                        new
                        {
                            ID = 78,
                            AppointmentTime = new DateTime(2024, 12, 13, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 197
                        },
                        new
                        {
                            ID = 79,
                            AppointmentTime = new DateTime(2024, 8, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 20,
                            PatientID = 5
                        },
                        new
                        {
                            ID = 80,
                            AppointmentTime = new DateTime(2024, 9, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 7,
                            PatientID = 3
                        },
                        new
                        {
                            ID = 81,
                            AppointmentTime = new DateTime(2025, 1, 24, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 19,
                            PatientID = 57
                        },
                        new
                        {
                            ID = 82,
                            AppointmentTime = new DateTime(2024, 7, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 78
                        },
                        new
                        {
                            ID = 83,
                            AppointmentTime = new DateTime(2024, 2, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 80
                        },
                        new
                        {
                            ID = 84,
                            AppointmentTime = new DateTime(2025, 9, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 40
                        },
                        new
                        {
                            ID = 85,
                            AppointmentTime = new DateTime(2024, 3, 21, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 19,
                            PatientID = 64
                        },
                        new
                        {
                            ID = 86,
                            AppointmentTime = new DateTime(2024, 11, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 6,
                            PatientID = 176
                        },
                        new
                        {
                            ID = 87,
                            AppointmentTime = new DateTime(2024, 2, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 17,
                            PatientID = 137
                        },
                        new
                        {
                            ID = 88,
                            AppointmentTime = new DateTime(2024, 1, 30, 14, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 90
                        },
                        new
                        {
                            ID = 89,
                            AppointmentTime = new DateTime(2025, 9, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 8,
                            PatientID = 125
                        },
                        new
                        {
                            ID = 90,
                            AppointmentTime = new DateTime(2024, 4, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 16,
                            PatientID = 178
                        },
                        new
                        {
                            ID = 91,
                            AppointmentTime = new DateTime(2024, 11, 28, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 95
                        },
                        new
                        {
                            ID = 92,
                            AppointmentTime = new DateTime(2025, 9, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 12,
                            PatientID = 199
                        },
                        new
                        {
                            ID = 93,
                            AppointmentTime = new DateTime(2025, 5, 22, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 10,
                            PatientID = 196
                        },
                        new
                        {
                            ID = 94,
                            AppointmentTime = new DateTime(2024, 6, 13, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 17,
                            PatientID = 122
                        },
                        new
                        {
                            ID = 95,
                            AppointmentTime = new DateTime(2025, 1, 25, 7, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 18,
                            PatientID = 198
                        },
                        new
                        {
                            ID = 96,
                            AppointmentTime = new DateTime(2025, 5, 29, 11, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 17,
                            PatientID = 2
                        },
                        new
                        {
                            ID = 97,
                            AppointmentTime = new DateTime(2025, 9, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 3,
                            PatientID = 12
                        },
                        new
                        {
                            ID = 98,
                            AppointmentTime = new DateTime(2024, 12, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 9,
                            PatientID = 93
                        },
                        new
                        {
                            ID = 99,
                            AppointmentTime = new DateTime(2025, 6, 6, 6, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 15,
                            PatientID = 185
                        },
                        new
                        {
                            ID = 100,
                            AppointmentTime = new DateTime(2025, 9, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            DoctorID = 14,
                            PatientID = 103
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("ID");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FullName = "Supreme Dr. Miranda Sugarmore"
                        },
                        new
                        {
                            ID = 2,
                            FullName = "Supreme Dr. Miranda Snackwell"
                        },
                        new
                        {
                            ID = 3,
                            FullName = "Doctor Penelope Sodamore"
                        },
                        new
                        {
                            ID = 4,
                            FullName = "M.D. Montgomery Sugarmore"
                        },
                        new
                        {
                            ID = 5,
                            FullName = "Master Dr. Geoffrey Colamore"
                        },
                        new
                        {
                            ID = 6,
                            FullName = "Doc. Benedict Jones"
                        },
                        new
                        {
                            ID = 7,
                            FullName = "Supreme Dr. Nathaniel Sugarlove"
                        },
                        new
                        {
                            ID = 8,
                            FullName = "Specialist Edmund Jones"
                        },
                        new
                        {
                            ID = 9,
                            FullName = "M.D. Chawton Sugarlove"
                        },
                        new
                        {
                            ID = 10,
                            FullName = "Supreme Dr. Alexander Colamore"
                        },
                        new
                        {
                            ID = 11,
                            FullName = "Master Dr. Sebastian Butterbliss"
                        },
                        new
                        {
                            ID = 12,
                            FullName = "Supreme Dr. Edmund Sodamore"
                        },
                        new
                        {
                            ID = 13,
                            FullName = "Specialist Leopold Snackright"
                        },
                        new
                        {
                            ID = 14,
                            FullName = "Master Dr. Benedict Snackwell"
                        },
                        new
                        {
                            ID = 15,
                            FullName = "M.D. Lavinia Chocofix"
                        },
                        new
                        {
                            ID = 16,
                            FullName = "Master Dr. Dorian Snackright"
                        },
                        new
                        {
                            ID = 17,
                            FullName = "PhD Dr. Oliver Sugarlove"
                        },
                        new
                        {
                            ID = 18,
                            FullName = "Professor Leopold Snackright"
                        },
                        new
                        {
                            ID = 19,
                            FullName = "Supreme Dr. Lavinia Sugarlove"
                        },
                        new
                        {
                            ID = 20,
                            FullName = "Doctor Josephine Chocofix"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Patient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("ID");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FullName = "Frank Smith"
                        },
                        new
                        {
                            ID = 2,
                            FullName = "Grace Martinez"
                        },
                        new
                        {
                            ID = 3,
                            FullName = "Emily Davis"
                        },
                        new
                        {
                            ID = 4,
                            FullName = "Grace Jackson"
                        },
                        new
                        {
                            ID = 5,
                            FullName = "Greg Williams"
                        },
                        new
                        {
                            ID = 6,
                            FullName = "Diane Martinez"
                        },
                        new
                        {
                            ID = 7,
                            FullName = "Diane Jackson"
                        },
                        new
                        {
                            ID = 8,
                            FullName = "Anna Thomas"
                        },
                        new
                        {
                            ID = 9,
                            FullName = "Grace Smith"
                        },
                        new
                        {
                            ID = 10,
                            FullName = "John Robinson"
                        },
                        new
                        {
                            ID = 11,
                            FullName = "Beth Garcia"
                        },
                        new
                        {
                            ID = 12,
                            FullName = "Ben Taylor"
                        },
                        new
                        {
                            ID = 13,
                            FullName = "Anna Thomas"
                        },
                        new
                        {
                            ID = 14,
                            FullName = "Dave Davis"
                        },
                        new
                        {
                            ID = 15,
                            FullName = "Ian Johnson"
                        },
                        new
                        {
                            ID = 16,
                            FullName = "Chris Garcia"
                        },
                        new
                        {
                            ID = 17,
                            FullName = "Emily Martin"
                        },
                        new
                        {
                            ID = 18,
                            FullName = "John Anderson"
                        },
                        new
                        {
                            ID = 19,
                            FullName = "Emily Anderson"
                        },
                        new
                        {
                            ID = 20,
                            FullName = "Ian Jackson"
                        },
                        new
                        {
                            ID = 21,
                            FullName = "Julia Thompson"
                        },
                        new
                        {
                            ID = 22,
                            FullName = "Beth Smith"
                        },
                        new
                        {
                            ID = 23,
                            FullName = "Dave Taylor"
                        },
                        new
                        {
                            ID = 24,
                            FullName = "Frank White"
                        },
                        new
                        {
                            ID = 25,
                            FullName = "Frank Taylor"
                        },
                        new
                        {
                            ID = 26,
                            FullName = "Dave Harris"
                        },
                        new
                        {
                            ID = 27,
                            FullName = "Emily Taylor"
                        },
                        new
                        {
                            ID = 28,
                            FullName = "Greg Thompson"
                        },
                        new
                        {
                            ID = 29,
                            FullName = "Diane Johnson"
                        },
                        new
                        {
                            ID = 30,
                            FullName = "Jack Davis"
                        },
                        new
                        {
                            ID = 31,
                            FullName = "John Thomas"
                        },
                        new
                        {
                            ID = 32,
                            FullName = "Anna Martin"
                        },
                        new
                        {
                            ID = 33,
                            FullName = "Diane Thomas"
                        },
                        new
                        {
                            ID = 34,
                            FullName = "Dave Harris"
                        },
                        new
                        {
                            ID = 35,
                            FullName = "Frank White"
                        },
                        new
                        {
                            ID = 36,
                            FullName = "Emily Smith"
                        },
                        new
                        {
                            ID = 37,
                            FullName = "Frank Williams"
                        },
                        new
                        {
                            ID = 38,
                            FullName = "Jack Thomas"
                        },
                        new
                        {
                            ID = 39,
                            FullName = "Dave Martin"
                        },
                        new
                        {
                            ID = 40,
                            FullName = "Ben Thomas"
                        },
                        new
                        {
                            ID = 41,
                            FullName = "Julia Taylor"
                        },
                        new
                        {
                            ID = 42,
                            FullName = "Chris Taylor"
                        },
                        new
                        {
                            ID = 43,
                            FullName = "Ben Davis"
                        },
                        new
                        {
                            ID = 44,
                            FullName = "Claire White"
                        },
                        new
                        {
                            ID = 45,
                            FullName = "Julia Williams"
                        },
                        new
                        {
                            ID = 46,
                            FullName = "Diane Williams"
                        },
                        new
                        {
                            ID = 47,
                            FullName = "Chris Taylor"
                        },
                        new
                        {
                            ID = 48,
                            FullName = "Jack Brown"
                        },
                        new
                        {
                            ID = 49,
                            FullName = "Grace Davis"
                        },
                        new
                        {
                            ID = 50,
                            FullName = "Grace Johnson"
                        },
                        new
                        {
                            ID = 51,
                            FullName = "Emily White"
                        },
                        new
                        {
                            ID = 52,
                            FullName = "Greg Wilson"
                        },
                        new
                        {
                            ID = 53,
                            FullName = "Anna Robinson"
                        },
                        new
                        {
                            ID = 54,
                            FullName = "Jack Smith"
                        },
                        new
                        {
                            ID = 55,
                            FullName = "Greg Miller"
                        },
                        new
                        {
                            ID = 56,
                            FullName = "John Moore"
                        },
                        new
                        {
                            ID = 57,
                            FullName = "Diane Garcia"
                        },
                        new
                        {
                            ID = 58,
                            FullName = "Chris Anderson"
                        },
                        new
                        {
                            ID = 59,
                            FullName = "Diane Wilson"
                        },
                        new
                        {
                            ID = 60,
                            FullName = "Jack Harris"
                        },
                        new
                        {
                            ID = 61,
                            FullName = "Chris Anderson"
                        },
                        new
                        {
                            ID = 62,
                            FullName = "Grace Anderson"
                        },
                        new
                        {
                            ID = 63,
                            FullName = "Julia Thomas"
                        },
                        new
                        {
                            ID = 64,
                            FullName = "Dave Johnson"
                        },
                        new
                        {
                            ID = 65,
                            FullName = "Jack Davis"
                        },
                        new
                        {
                            ID = 66,
                            FullName = "Emily Brown"
                        },
                        new
                        {
                            ID = 67,
                            FullName = "Greg Anderson"
                        },
                        new
                        {
                            ID = 68,
                            FullName = "Emily Martin"
                        },
                        new
                        {
                            ID = 69,
                            FullName = "Emily Robinson"
                        },
                        new
                        {
                            ID = 70,
                            FullName = "Ian Brown"
                        },
                        new
                        {
                            ID = 71,
                            FullName = "Greg Thomas"
                        },
                        new
                        {
                            ID = 72,
                            FullName = "John Davis"
                        },
                        new
                        {
                            ID = 73,
                            FullName = "Ben Martinez"
                        },
                        new
                        {
                            ID = 74,
                            FullName = "Claire Anderson"
                        },
                        new
                        {
                            ID = 75,
                            FullName = "Ben Martin"
                        },
                        new
                        {
                            ID = 76,
                            FullName = "Ian Davis"
                        },
                        new
                        {
                            ID = 77,
                            FullName = "Diane Garcia"
                        },
                        new
                        {
                            ID = 78,
                            FullName = "Beth Taylor"
                        },
                        new
                        {
                            ID = 79,
                            FullName = "Beth Johnson"
                        },
                        new
                        {
                            ID = 80,
                            FullName = "Greg Martinez"
                        },
                        new
                        {
                            ID = 81,
                            FullName = "Dave Martin"
                        },
                        new
                        {
                            ID = 82,
                            FullName = "Frank Davis"
                        },
                        new
                        {
                            ID = 83,
                            FullName = "Dave Martinez"
                        },
                        new
                        {
                            ID = 84,
                            FullName = "Julia Harris"
                        },
                        new
                        {
                            ID = 85,
                            FullName = "Greg Miller"
                        },
                        new
                        {
                            ID = 86,
                            FullName = "Emily Garcia"
                        },
                        new
                        {
                            ID = 87,
                            FullName = "Greg Robinson"
                        },
                        new
                        {
                            ID = 88,
                            FullName = "Beth Martinez"
                        },
                        new
                        {
                            ID = 89,
                            FullName = "Emily Taylor"
                        },
                        new
                        {
                            ID = 90,
                            FullName = "Ian Harris"
                        },
                        new
                        {
                            ID = 91,
                            FullName = "Grace Miller"
                        },
                        new
                        {
                            ID = 92,
                            FullName = "Ian Williams"
                        },
                        new
                        {
                            ID = 93,
                            FullName = "Anna Martin"
                        },
                        new
                        {
                            ID = 94,
                            FullName = "Julia Robinson"
                        },
                        new
                        {
                            ID = 95,
                            FullName = "Jack Martin"
                        },
                        new
                        {
                            ID = 96,
                            FullName = "Beth Wilson"
                        },
                        new
                        {
                            ID = 97,
                            FullName = "Greg Jackson"
                        },
                        new
                        {
                            ID = 98,
                            FullName = "Greg Harris"
                        },
                        new
                        {
                            ID = 99,
                            FullName = "Claire Williams"
                        },
                        new
                        {
                            ID = 100,
                            FullName = "Chris White"
                        },
                        new
                        {
                            ID = 101,
                            FullName = "Frank White"
                        },
                        new
                        {
                            ID = 102,
                            FullName = "Emily Garcia"
                        },
                        new
                        {
                            ID = 103,
                            FullName = "Greg Robinson"
                        },
                        new
                        {
                            ID = 104,
                            FullName = "Emily Harris"
                        },
                        new
                        {
                            ID = 105,
                            FullName = "Beth Taylor"
                        },
                        new
                        {
                            ID = 106,
                            FullName = "Chris Williams"
                        },
                        new
                        {
                            ID = 107,
                            FullName = "Greg Johnson"
                        },
                        new
                        {
                            ID = 108,
                            FullName = "Jack Moore"
                        },
                        new
                        {
                            ID = 109,
                            FullName = "Grace Taylor"
                        },
                        new
                        {
                            ID = 110,
                            FullName = "Ian Williams"
                        },
                        new
                        {
                            ID = 111,
                            FullName = "Greg Williams"
                        },
                        new
                        {
                            ID = 112,
                            FullName = "Anna Martin"
                        },
                        new
                        {
                            ID = 113,
                            FullName = "Diane Taylor"
                        },
                        new
                        {
                            ID = 114,
                            FullName = "Beth Taylor"
                        },
                        new
                        {
                            ID = 115,
                            FullName = "Jack Anderson"
                        },
                        new
                        {
                            ID = 116,
                            FullName = "Greg Miller"
                        },
                        new
                        {
                            ID = 117,
                            FullName = "Beth Thomas"
                        },
                        new
                        {
                            ID = 118,
                            FullName = "John Garcia"
                        },
                        new
                        {
                            ID = 119,
                            FullName = "Grace Garcia"
                        },
                        new
                        {
                            ID = 120,
                            FullName = "Grace Williams"
                        },
                        new
                        {
                            ID = 121,
                            FullName = "John Anderson"
                        },
                        new
                        {
                            ID = 122,
                            FullName = "Jack Moore"
                        },
                        new
                        {
                            ID = 123,
                            FullName = "Beth Thompson"
                        },
                        new
                        {
                            ID = 124,
                            FullName = "Ian Smith"
                        },
                        new
                        {
                            ID = 125,
                            FullName = "Grace Thompson"
                        },
                        new
                        {
                            ID = 126,
                            FullName = "Ben Johnson"
                        },
                        new
                        {
                            ID = 127,
                            FullName = "Ben Thomas"
                        },
                        new
                        {
                            ID = 128,
                            FullName = "Jack Robinson"
                        },
                        new
                        {
                            ID = 129,
                            FullName = "Anna Wilson"
                        },
                        new
                        {
                            ID = 130,
                            FullName = "Beth Williams"
                        },
                        new
                        {
                            ID = 131,
                            FullName = "Anna Anderson"
                        },
                        new
                        {
                            ID = 132,
                            FullName = "Frank Miller"
                        },
                        new
                        {
                            ID = 133,
                            FullName = "Ben Robinson"
                        },
                        new
                        {
                            ID = 134,
                            FullName = "Greg Wilson"
                        },
                        new
                        {
                            ID = 135,
                            FullName = "Greg Thompson"
                        },
                        new
                        {
                            ID = 136,
                            FullName = "Jack Martin"
                        },
                        new
                        {
                            ID = 137,
                            FullName = "Chris Johnson"
                        },
                        new
                        {
                            ID = 138,
                            FullName = "Claire Harris"
                        },
                        new
                        {
                            ID = 139,
                            FullName = "Diane Taylor"
                        },
                        new
                        {
                            ID = 140,
                            FullName = "John Thompson"
                        },
                        new
                        {
                            ID = 141,
                            FullName = "Dave Johnson"
                        },
                        new
                        {
                            ID = 142,
                            FullName = "Grace Johnson"
                        },
                        new
                        {
                            ID = 143,
                            FullName = "Emily White"
                        },
                        new
                        {
                            ID = 144,
                            FullName = "Beth Martinez"
                        },
                        new
                        {
                            ID = 145,
                            FullName = "Chris Smith"
                        },
                        new
                        {
                            ID = 146,
                            FullName = "Beth Taylor"
                        },
                        new
                        {
                            ID = 147,
                            FullName = "Greg Martinez"
                        },
                        new
                        {
                            ID = 148,
                            FullName = "Beth Jackson"
                        },
                        new
                        {
                            ID = 149,
                            FullName = "Jack White"
                        },
                        new
                        {
                            ID = 150,
                            FullName = "Frank Thomas"
                        },
                        new
                        {
                            ID = 151,
                            FullName = "Anna Jackson"
                        },
                        new
                        {
                            ID = 152,
                            FullName = "Diane Johnson"
                        },
                        new
                        {
                            ID = 153,
                            FullName = "Ben Smith"
                        },
                        new
                        {
                            ID = 154,
                            FullName = "Frank Thompson"
                        },
                        new
                        {
                            ID = 155,
                            FullName = "Beth Miller"
                        },
                        new
                        {
                            ID = 156,
                            FullName = "Julia Robinson"
                        },
                        new
                        {
                            ID = 157,
                            FullName = "Chris Martin"
                        },
                        new
                        {
                            ID = 158,
                            FullName = "Emily Thomas"
                        },
                        new
                        {
                            ID = 159,
                            FullName = "Emily Taylor"
                        },
                        new
                        {
                            ID = 160,
                            FullName = "John Jackson"
                        },
                        new
                        {
                            ID = 161,
                            FullName = "Chris Davis"
                        },
                        new
                        {
                            ID = 162,
                            FullName = "Diane Miller"
                        },
                        new
                        {
                            ID = 163,
                            FullName = "Jack Taylor"
                        },
                        new
                        {
                            ID = 164,
                            FullName = "Chris Harris"
                        },
                        new
                        {
                            ID = 165,
                            FullName = "Jack Smith"
                        },
                        new
                        {
                            ID = 166,
                            FullName = "Emily Jackson"
                        },
                        new
                        {
                            ID = 167,
                            FullName = "Grace Anderson"
                        },
                        new
                        {
                            ID = 168,
                            FullName = "Claire White"
                        },
                        new
                        {
                            ID = 169,
                            FullName = "Jack Davis"
                        },
                        new
                        {
                            ID = 170,
                            FullName = "Claire Taylor"
                        },
                        new
                        {
                            ID = 171,
                            FullName = "Jack Moore"
                        },
                        new
                        {
                            ID = 172,
                            FullName = "Claire Taylor"
                        },
                        new
                        {
                            ID = 173,
                            FullName = "Dave Thompson"
                        },
                        new
                        {
                            ID = 174,
                            FullName = "Chris Harris"
                        },
                        new
                        {
                            ID = 175,
                            FullName = "Claire Smith"
                        },
                        new
                        {
                            ID = 176,
                            FullName = "Emily Martin"
                        },
                        new
                        {
                            ID = 177,
                            FullName = "Ben Smith"
                        },
                        new
                        {
                            ID = 178,
                            FullName = "Anna Smith"
                        },
                        new
                        {
                            ID = 179,
                            FullName = "John Johnson"
                        },
                        new
                        {
                            ID = 180,
                            FullName = "Beth Brown"
                        },
                        new
                        {
                            ID = 181,
                            FullName = "Ben Garcia"
                        },
                        new
                        {
                            ID = 182,
                            FullName = "Ben Williams"
                        },
                        new
                        {
                            ID = 183,
                            FullName = "Emily Thompson"
                        },
                        new
                        {
                            ID = 184,
                            FullName = "Jack Harris"
                        },
                        new
                        {
                            ID = 185,
                            FullName = "Diane Miller"
                        },
                        new
                        {
                            ID = 186,
                            FullName = "Dave Thompson"
                        },
                        new
                        {
                            ID = 187,
                            FullName = "Beth Garcia"
                        },
                        new
                        {
                            ID = 188,
                            FullName = "Anna Brown"
                        },
                        new
                        {
                            ID = 189,
                            FullName = "Anna Brown"
                        },
                        new
                        {
                            ID = 190,
                            FullName = "Ian Martin"
                        },
                        new
                        {
                            ID = 191,
                            FullName = "Jack Wilson"
                        },
                        new
                        {
                            ID = 192,
                            FullName = "Greg Davis"
                        },
                        new
                        {
                            ID = 193,
                            FullName = "Anna Thompson"
                        },
                        new
                        {
                            ID = 194,
                            FullName = "Diane Williams"
                        },
                        new
                        {
                            ID = 195,
                            FullName = "Grace Smith"
                        },
                        new
                        {
                            ID = 196,
                            FullName = "Ian Brown"
                        },
                        new
                        {
                            ID = 197,
                            FullName = "Claire Harris"
                        },
                        new
                        {
                            ID = 198,
                            FullName = "Anna Martinez"
                        },
                        new
                        {
                            ID = 199,
                            FullName = "Dave Taylor"
                        },
                        new
                        {
                            ID = 200,
                            FullName = "Beth Martin"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Appointment", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Domain.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workshop.wwwapi.Models.Domain.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Domain.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
