// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240202110219_data_test")]
    partial class data_test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.DatabaseModels.Appointment", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_doctor_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("fk_patient_id");

                    b.Property<DateTimeOffset>("Booking")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.HasKey("DoctorId", "PatientId")
                        .HasName("PJ_appoitment_doctor_patient");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            PatientId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 3, 12, 2, 19, 544, DateTimeKind.Unspecified).AddTicks(144), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            DoctorId = 1,
                            PatientId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 7, 12, 2, 19, 544, DateTimeKind.Unspecified).AddTicks(150), new TimeSpan(0, 1, 0, 0, 0))
                        },
                        new
                        {
                            DoctorId = 2,
                            PatientId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 5, 2, 12, 2, 19, 544, DateTimeKind.Unspecified).AddTicks(153), new TimeSpan(0, 2, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.DatabaseModels.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Oprah Obama"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Charles Winfrey"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Kate Windsor"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Jimi Presley"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Charles Winfrey"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Audrey Winfrey"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Audrey Presley"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Mick Presley"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Jimi Jagger"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Kate Windsor"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Elvis Presley"
                        },
                        new
                        {
                            Id = 16,
                            FullName = "Barack Windsor"
                        },
                        new
                        {
                            Id = 17,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 18,
                            FullName = "Barack Jagger"
                        },
                        new
                        {
                            Id = 19,
                            FullName = "Jimi Hendrix"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.DatabaseModels.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Kate Windsor"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Donald Obama"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Barack Winslet"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Kate Trump"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Barack Middleton"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Kate Obama"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Jimi Winfrey"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Oprah Winslet"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Oprah Winslet"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Elvis Obama"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Barack Winslet"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Donald Presley"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Barack Obama"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Donald Winslet"
                        },
                        new
                        {
                            Id = 16,
                            FullName = "Audrey Winslet"
                        },
                        new
                        {
                            Id = 17,
                            FullName = "Barack Presley"
                        },
                        new
                        {
                            Id = 18,
                            FullName = "Oprah Middleton"
                        },
                        new
                        {
                            Id = 19,
                            FullName = "Elvis Hepburn"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
