// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240910103515_eleventhMigration")]
    partial class eleventhMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctorId");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patientId");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("prescription_id");

                    b.Property<DateTime>("Booking")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("DoctorId", "PatientId", "PrescriptionId");

                    b.ToTable("appointments");

                    b.HasData(
                        new
                        {
                            DoctorId = 6,
                            PatientId = 1,
                            PrescriptionId = 1,
                            Booking = new DateTime(2024, 10, 18, 5, 38, 48, 955, DateTimeKind.Utc).AddTicks(1844),
                            Id = 1
                        },
                        new
                        {
                            DoctorId = 5,
                            PatientId = 2,
                            PrescriptionId = 2,
                            Booking = new DateTime(2025, 8, 18, 9, 37, 4, 955, DateTimeKind.Utc).AddTicks(1952),
                            Id = 2
                        },
                        new
                        {
                            DoctorId = 2,
                            PatientId = 3,
                            PrescriptionId = 3,
                            Booking = new DateTime(2025, 6, 22, 11, 33, 13, 955, DateTimeKind.Utc).AddTicks(1960),
                            Id = 3
                        },
                        new
                        {
                            DoctorId = 5,
                            PatientId = 4,
                            PrescriptionId = 4,
                            Booking = new DateTime(2025, 5, 20, 2, 6, 52, 955, DateTimeKind.Utc).AddTicks(1982),
                            Id = 4
                        },
                        new
                        {
                            DoctorId = 7,
                            PatientId = 5,
                            PrescriptionId = 5,
                            Booking = new DateTime(2024, 12, 21, 11, 34, 39, 955, DateTimeKind.Utc).AddTicks(1987),
                            Id = 5
                        },
                        new
                        {
                            DoctorId = 4,
                            PatientId = 6,
                            PrescriptionId = 6,
                            Booking = new DateTime(2024, 11, 4, 14, 56, 43, 955, DateTimeKind.Utc).AddTicks(1995),
                            Id = 6
                        },
                        new
                        {
                            DoctorId = 8,
                            PatientId = 7,
                            PrescriptionId = 7,
                            Booking = new DateTime(2024, 11, 5, 18, 26, 9, 955, DateTimeKind.Utc).AddTicks(1999),
                            Id = 7
                        },
                        new
                        {
                            DoctorId = 7,
                            PatientId = 8,
                            PrescriptionId = 8,
                            Booking = new DateTime(2024, 9, 16, 1, 49, 53, 955, DateTimeKind.Utc).AddTicks(2002),
                            Id = 8
                        },
                        new
                        {
                            DoctorId = 4,
                            PatientId = 9,
                            PrescriptionId = 9,
                            Booking = new DateTime(2025, 8, 7, 17, 16, 17, 955, DateTimeKind.Utc).AddTicks(2011),
                            Id = 9
                        },
                        new
                        {
                            DoctorId = 6,
                            PatientId = 10,
                            PrescriptionId = 10,
                            Booking = new DateTime(2025, 8, 1, 3, 8, 56, 955, DateTimeKind.Utc).AddTicks(2015),
                            Id = 10
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.HasKey("Id");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Elvis Winslow"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Adam Obama"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Arnold Schwarzenegger"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Elvis Mouse"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Charles Mouse"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Felix Lothbrok"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Felix Xavier"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Barack Duck"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Elvis Lothbrok"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Arnold Andersson"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.ToTable("medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instruction = "Lick over a long period of time.",
                            Name = "Not Laxatives",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 2,
                            Instruction = "Lick over a long period of time.",
                            Name = "Stupid Drugs",
                            Quantity = 89
                        },
                        new
                        {
                            Id = 3,
                            Instruction = "Chew on it for 3 hours.",
                            Name = "Yummy Aspirin",
                            Quantity = 87
                        },
                        new
                        {
                            Id = 4,
                            Instruction = "Swallow with water.",
                            Name = "Super Mushrooms",
                            Quantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Instruction = "Disolve into drink of your choice.",
                            Name = "Bad Pills",
                            Quantity = 99
                        },
                        new
                        {
                            Id = 6,
                            Instruction = "Lick over a long period of time.",
                            Name = "Ultra Laxatives",
                            Quantity = 86
                        },
                        new
                        {
                            Id = 7,
                            Instruction = "Insert into rectum.",
                            Name = "Yummy Morphine",
                            Quantity = 90
                        },
                        new
                        {
                            Id = 8,
                            Instruction = "Hide in cabinet and let the placebo effect do it's job.",
                            Name = "Bad Mushrooms",
                            Quantity = 99
                        },
                        new
                        {
                            Id = 9,
                            Instruction = "Swallow with water.",
                            Name = "Bad Potion",
                            Quantity = 62
                        },
                        new
                        {
                            Id = 10,
                            Instruction = "Insert into rectum.",
                            Name = "Not Heroin",
                            Quantity = 63
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullName");

                    b.HasKey("Id");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Neo Schwarzenegger"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Kate Lothbrok"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Oprah Obama"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Neo Andersson"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Ragnar Winslow"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Barack Duck"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Adam Sandler"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Mickey Lothbrok"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Donald Andersson"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Kate Schwarzenegger"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        },
                        new
                        {
                            Id = 7
                        },
                        new
                        {
                            Id = 8
                        },
                        new
                        {
                            Id = 9
                        },
                        new
                        {
                            Id = 10
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.PrescriptionMedicine", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("prescription_id");

                    b.Property<int>("MedicineId")
                        .HasColumnType("integer")
                        .HasColumnName("medicine_id");

                    b.HasKey("PrescriptionId", "MedicineId");

                    b.HasIndex("MedicineId");

                    b.ToTable("prescription_medicines");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 1
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 5,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 2
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 2,
                            MedicineId = 3
                        },
                        new
                        {
                            PrescriptionId = 9,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 4
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 5
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 10,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 6
                        },
                        new
                        {
                            PrescriptionId = 4,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 7
                        },
                        new
                        {
                            PrescriptionId = 10,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 6,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 1,
                            MedicineId = 8
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 9
                        },
                        new
                        {
                            PrescriptionId = 3,
                            MedicineId = 10
                        },
                        new
                        {
                            PrescriptionId = 7,
                            MedicineId = 10
                        },
                        new
                        {
                            PrescriptionId = 8,
                            MedicineId = 10
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.PrescriptionMedicine", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workshop.wwwapi.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Medicine", b =>
                {
                    b.Navigation("PrescriptionMedicines");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionMedicines");
                });
#pragma warning restore 612, 618
        }
    }
}
