// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240207101852_UpdateToDatatablesMigration4")]
    partial class UpdateToDatatablesMigration4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.Property<int>("PatientIdFK")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id_fk");

                    b.Property<int>("DoctorIdFK")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id_fk");

                    b.Property<DateTime>("Booking")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("PatientIdFK", "DoctorIdFK", "Booking");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments");

                    b.HasData(
                        new
                        {
                            PatientIdFK = 2,
                            DoctorIdFK = 1,
                            Booking = new DateTime(2020, 4, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 1
                        },
                        new
                        {
                            PatientIdFK = 1,
                            DoctorIdFK = 2,
                            Booking = new DateTime(2020, 1, 13, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Id = 2
                        },
                        new
                        {
                            PatientIdFK = 1,
                            DoctorIdFK = 1,
                            Booking = new DateTime(2020, 10, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Id = 3
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Dr. Jason Bourne"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Dr. Mats Anderson"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Jack Peterson"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Dave Davidson"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Doctor", null)
                        .WithMany("appointments")
                        .HasForeignKey("DoctorId");

                    b.HasOne("workshop.wwwapi.Models.Patient", null)
                        .WithMany("appointments")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Navigation("appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
